kottans/frontend-2019-p2p

- CONTRIBUTING.md
I add `Codereview` section And delete `Merging the PR`
> Proposal changes got p2p homework CONTRIBUTING.md

- code-review-guidelines.md
Partially resolves issue #1 
The document contains many TBA parts and may serve as a basis for code review guidelines. Important parts which are missing:
- Tone & attitude guidelines
- OOP code review guidelines
- HTML & CSS code review guidelines
> update code review guidelines

- submissions/Roka20012/a-tiny-JS-world-oop/index.js
a-tiny-JS-world-oop
[Demo](https://roka20012.github.io/a-tiny-JS-world/) |
[Code base](https://github.com/Roka20012/kottans_frontend/blob/master/practical_task/a-tiny-JS-world/index.js)
> a-tiny-JS-world-oop done

- submissions/Roka20012/js-oop/app.js
js-oop
[Demo](https://roka20012.github.io/js-oop/) |
[Code base](https://github.com/Roka20012/kottans_frontend/tree/master/practical_task/js-oop)
> js-oop done

- submissions/Zakkarat/a-tiny-JS-world/index.js
[Demo](https://zakkarat.github.io/a-tiny-JS-world/index.html) |
[Code base](https://github.com/Zakkarat/a-tiny-JS-world)
> Tiny JS world

- submissions/Zakkarat/js-dom/app.js
- submissions/Zakkarat/js-dom/index.html
- submissions/Zakkarat/js-dom/stylesheet/hamburger.css
- submissions/Zakkarat/js-dom/stylesheet/main.css
[Demo](https://zakkarat.github.io/DOM_TASK/index.html) |
[Code base](https://github.com/Zakkarat/DOM_TASK)
> dom-api-task

- submissions/korotushak96/a-tiny-JS-world/index.js
_Replace task name and links as appropriate and remove this line._
[Demo](https://korotushak96.github.io/a-tiny-JS-world/) |
[Code base](https://github.com/korotushak96/a-tiny-JS-world)
> tiny JS world --done

- submissions/Zakkarat/memory-pair-game/app.js
- submissions/Zakkarat/memory-pair-game/index.html
- submissions/Zakkarat/memory-pair-game/stylesheet/main.css
[Demo](https://zakkarat.github.io/memory-pair-game/) |
[Code base](https://github.com/Zakkarat/memory-pair-game)
> Memory Pair Game

- submissions/Zakkarat/html-css-popup/css/main.css
- submissions/Zakkarat/html-css-popup/css/reset.css
- submissions/Zakkarat/html-css-popup/index.html
[Demo](https://zakkarat.github.io/popup-menu/) |
[Code base](https://github.com/Zakkarat/popup-menu)
> Html css popup

- submissions/aymkin/HTML-CSS-Popup/README.md
The (original README.MD)[https://github.com/kottans/frontend-2019-p2p/commit/99c1076e7120cac5cc831975232d43d56c86ae02] was overwritten by pull request #57. 
Please restore the original Readme file.
THX
> restore original README.md

- CONTRIBUTING.md
- submissions/aymkin/HTML-CSS-Popup/README.md
Changed links to the relevant ones
> Fix invalid links in CONTRIBUTING.md

- submissions/madmaxWMFU/a-tiny-JS-world-OOP/index.js
[Demo](https://madmaxwmfu.github.io/a-tiny-JS-world/) |
[Code base](https://github.com/madmaxwmfu/a-tiny-JS-world/blob/gh-pages/index.js)
> a tiny js world oop

- submissions/Temu4/tiny-js-world-oop/index.js
[Demo](https://temu4.github.io/a-tiny-JS-world-oop/) |
[Code base](https://github.com/Temu4/frontend-2019-p2p/tree/tiny-js-world-oop/submissions/Temu4/tiny-js-world-oop)
Redesigned according to OOP. 
> tiny-js-world-oop done

- submissions/Zakkarat/html-forms/index.html
- submissions/Zakkarat/html-forms/stylesheet/choose-document.css
- submissions/Zakkarat/html-forms/stylesheet/footer.css
- submissions/Zakkarat/html-forms/stylesheet/header.css
- submissions/Zakkarat/html-forms/stylesheet/language-choose.css
- submissions/Zakkarat/html-forms/stylesheet/main.css
- submissions/Zakkarat/html-forms/stylesheet/normalize.css
- submissions/Zakkarat/html-forms/stylesheet/payment.css
- submissions/Zakkarat/html-forms/stylesheet/tone-time.css
- submissions/Zakkarat/html-forms/stylesheet/upload.css
[Demo](https://zakkarat.github.io/html-forms/) |
[Code base](https://github.com/Zakkarat/html-forms)
> Html forms

- submissions/sayckl/friends-app/index.html
- submissions/sayckl/friends-app/script.js
- submissions/sayckl/friends-app/style.css
[Demo](https://sayckl.github.io/friends-app/) |
[Code base](https://github.com/sayckl/frontend-2019-p2p/tree/friends-app-task/submissions/sayckl/friends-app)
> friends-app

- submissions/ArthurGorbenko/Friend's app/README.md
- submissions/ArthurGorbenko/Friend's app/css/hamburgers.css
- submissions/ArthurGorbenko/Friend's app/css/styles.css
- submissions/ArthurGorbenko/Friend's app/index.html
- submissions/ArthurGorbenko/Friend's app/js/script.js
[Demo](https://arthurgorbenko.github.io/Friend-s-app/) |
[Code base](https://github.com/ArthurGorbenko/Friend-s-app)
> Friend's app

- submissions/karelskiy/tiny-JS-world/index.js
[Demo](https://karelskiy.github.io/a-tiny-JS-world/) |
[Code base](https://github.com/karelskiy/a-tiny-JS-world/blob/gh-pages/index.js)
> tiny js world without oop

- submissions/dafen173/a-tiny-js-world/index.js
_Replace task name and links as appropriate and remove this line._
[Demo](https://dafen173.github.io/a-tiny-JS-world/) |
[Code base](https://github.com/dafen173/frontend-2019-p2p/blob/master-tiny-js-world/submissions/dafen173/a-tiny-js-world/index.js)
> add a-tiny-js-world to branch from master

- submissions/solaryasha/a-tiny-js-world-without-oop/index.js
[Demo](https://solaryasha.github.io/a-tiny-JS-world/) |
[Code base](https://github.com/solaryasha/a-tiny-JS-world/blob/master/index.js)
> A tiny JS world (without oop)

- submissions/dashakim/a-tiny-world2/index.js
_Replace task name and links as appropriate and remove this line._
[Demo](https://dashakim.github.io/a-tiny-JS-world/) |
[Code base](https://github.com/dashakim/a-tiny-JS-world/blob/master/index.js)
> Add task oop exercise - a tiny world

- submissions/NastjonkaK/a-tiny-JS-world/index.js
[Demo](https://nastjonkak.github.io/a-tiny-JS-world/) |
[Code base](https://github.com/NastjonkaK/a-tiny-JS-world/blob/master/index.js)
> a-tiny-JS-world

- submissions/xT0PERx/A-Tiny-JS-World/index.js
[Demo](https://xt0perx.github.io/a-tiny-JS-world/) |
[Code base](https://github.com/xT0PERx/frontend-2019-p2p/blob/A-Tiny-JS-World/submissions/xT0PERx/A-Tiny-JS-World/index.js)
> Added file with my home task TINY- JS-WORLD

- submissions/kris-almort/a-tiny-js-world/README.md
- submissions/kris-almort/a-tiny-js-world/index.js
- submissions/kris-almort/html-css-popup/README.md
_Replace task name and links as appropriate and remove this line._
[Demo](https://chris-voitova.github.io/a-tiny-JS-world/) |
[Code base](https://github.com/chris-voitova/a-tiny-JS-world/blob/master/index.js)
> A tiny js world

- submissions/SergeyShytikov/html-css-practice-task/index.html
- submissions/SergeyShytikov/html-css-practice-task/slyle.css
[Demo](https://sergeyshytikov.github.io/popupDemo/) |
[Code base](https://github.com/SergeyShytikov/popupDemo)
> html & css popup
